# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ce18735bd83d0cf4e23bab3a1fbc0960c0b78a16ddd121ab424c860d4d2c6d598a92805d6b400cb0e29a2e6958ad7eaca541fdd08d69f8199a4e9c3e8a5d2276

test:
  secret_key_base: ff83bf19180d3ccef121f9fc05434d0c13e492a5c06c4f915ab677b93c1c8f0cb6fe2eb4d48d9fe2aaa73cddaa8fe008676e9ce1b80bfca954654f2c846c2c91

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
